# Generated by Django 5.1.2 on 2024-10-22 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0002_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='country',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='series',
            name='year',
        ),
        migrations.AddField(
            model_name='episode',
            name='mover_url',
            field=models.URLField(default=django.utils.timezone.now, help_text='URL эпизода на mover.uz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_serires.episode'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_serires.comment'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_serires.category'),
        ),
        migrations.AlterField(
            model_name='series',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
