# Generated by Django 5.1.2 on 2024-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0003_remove_series_genres_remove_episode_trailer_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='category',
            new_name='country',
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='series', to='app_serires.genre'),
        ),
    ]
