# Generated by Django 5.1.2 on 2024-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0006_remove_episode_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
