# Generated by Django 5.1.2 on 2024-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0007_series_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
