# Generated by Django 5.1.2 on 2024-10-25 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0008_series_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, help_text='Выберите видеофайл', null=True, upload_to='episodes/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='mover_url',
            field=models.URLField(blank=True, help_text='URL эпизода на mover.uz', null=True),
        ),
    ]
