# Generated by Django 5.1.2 on 2024-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0009_episode_video_file_alter_episode_mover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='add_method',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'File')], default='url', max_length=10),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
    ]
