# Generated by Django 5.1.2 on 2024-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0010_episode_add_method_alter_episode_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
