# Generated by Django 5.1.2 on 2024-10-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0013_episode_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
