# Generated by Django 5.1.2 on 2024-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0014_episode_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
    ]
