# Generated by Django 5.1.2 on 2024-10-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serires', '0015_remove_episode_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], default='mon', max_length=3)),
                ('release_time', models.TimeField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_schedules', to='app_serires.series')),
            ],
        ),
    ]
